name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: xcode-27

    steps:
    - uses: actions/checkout@v7
    - name: Switch to latest Xcode
      run: sudo xcode-select -s "/Applications/Xcode_27.0.app/Contents/Developer"
    - name: Build
      run: xcodebuild -verbose -scheme carnival
