name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-carnival-glut:
    runs-on: xcode-27

    steps:
    - uses: actions/checkout@v7
    - name: Switch to latest Xcode
      run: sudo xcode-select -s "/Applications/Xcode_27.0.app/Contents/Developer"
    - name: Build CarnivalGLUT
      run: xcodebuild -verbose -scheme CarnivalGLUT

  build-carnival-screen-saver:
    runs-on: xcode-27

    steps:
    - uses: actions/checkout@v7
    - name: Switch to latest Xcode
      run: sudo xcode-select -s "/Applications/Xcode_27.0.app/Contents/Developer"
    - name: Install Metal Toolchain
      run: xcodebuild -downloadComponent MetalToolchain
    - name: Build CarnivalScreenSaver
      run: xcodebuild -verbose -scheme CarnivalScreenSaver

  build-carnival:
    runs-on: xcode-27

    strategy:
      fail-fast: false
      matrix:
        destination:
          - 'platform=macOS'
          - 'generic/platform=iOS Simulator'
          - 'generic/platform=tvOS Simulator'
          - 'generic/platform=visionOS Simulator'

    steps:
    - uses: actions/checkout@v7
    - name: Switch to latest Xcode
      run: sudo xcode-select -s "/Applications/Xcode_27.0.app/Contents/Developer"
    - name: Install Metal Toolchain
      run: xcodebuild -downloadComponent MetalToolchain
    - name: Build Carnival
      run: xcodebuild -verbose -scheme Carnival -destination '${{ matrix.destination }}'
